server:
  port: 8082

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: Battl3grounds
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296

#  eureka:
#    instance:
#      prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url:
#        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}





